apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-python-hpa
  namespace: sample-grafana
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-python-app
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
