apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-app-pvc
  namespace: sample-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
