apiVersion: v1
kind: Service
metadata:
  name: sample-python-svc
  namespace: sample-grafana
  labels:
    app: sample-python-app
spec:
  type: LoadBalancer
  selector:
    app: sample-python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
